### ISSUE TITLE
PROMPT_COMMAND support

### ISSUE THREAD

**Issue by f1urps** [sudofox/shell-mommy#1]
Hi, nice project!

I wanted to let you know there's a way to integrate with PROMPT_COMMAND without any changes to the script.

in .bashrc:
```
source /path/to/mommy.sh
export PROMPT_COMMAND="mommy \\$\\(exit \$?\\); $PROMPT_COMMAND"
```

You could add this note in the Readme to let users know.

**Comment by sudofox** [comment]
Just tested -- that works great, thanks!
