### ISSUE TITLE
?

### ISSUE THREAD

**Issue by TheGhostOfSudomemo** [sudofox/shell-mommy#31]
This is disgusting, why would you even think of making such a thing ?

**Comment by Tranberry** [comment]
Xe/Xem

**Comment by TheGhostOfSudomemo** [comment]
Not my real pronouns, but why mention them?

**Comment by sudofox** [comment]
> This is disgusting, why would you even think of making such a thing ?

for laughs, mostly. it's funny to see how people respond to such a thing existing.

I don't think it's particularly disgusting, though. I think it has worth in entertainment value and does not present any particular moral issues that I can think of. 

plus, you can have Samuel L Jackson insult you when you mistype

**Comment by meemo** [comment]
honi soit qui mal y pense
